"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from .base import *


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: str  # type: str

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS: list  # type: list[str]


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES: dict  # type: dict[str, dict[str, str]]


# Session Settings

SESSION_COOKIE_AGE = 3600  # default is 1209600 (two weeks)

SESSION_COOKIE_NAME = '{session-cookie-name}'

SESSION_COOKIE_SECURE = True  # for https

CSRF_COOKIE_SECURE = True  # for https


# Static Files Mapping - collectstatic

STATIC_ROOT = BASE_DIR / 'static_files'
